// Copyright 2026 Circle Internet Group, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#![allow(
    clippy::arithmetic_side_effects,
    clippy::cast_possible_truncation,
    clippy::unwrap_used
)]

use std::{collections::HashMap, fs, io::IsTerminal, io::Write, path::Path};

use clap::{Parser, Subcommand};
use clap_verbosity_flag::{InfoLevel, Verbosity};
use color_eyre::eyre::{self, Context, Result};
use serde::Deserialize;
use tracing_subscriber::EnvFilter;
use url::Url;

use spammer::{Spammer, SpammerArgs};

const DEFAULT_WS_TARGET: &str = "127.0.0.1:8546";

#[derive(Parser)]
#[command(
    name = "spammer",
    version = arc_version::SHORT_VERSION,
    long_version = arc_version::LONG_VERSION,
    about = "Spammer: transaction load generator and sender"
)]
struct Cli {
    /// Seed for deterministic execution
    #[arg(long, global = true)]
    seed: Option<u64>,
    /// Use fire-and-forget mode: push transactions into a buffered channel
    /// and send without waiting for responses. Nonces are incremented
    /// optimistically. By default the spammer uses backpressure mode.
    #[arg(long, default_value = "false", global = true)]
    fire_and_forget: bool,
    /// Spammer configuration
    #[command(flatten)]
    args: SpammerArgs,

    #[command(flatten)]
    verbosity: Verbosity<InfoLevel>,

    /// Target selection mode
    #[command(subcommand)]
    command: TargetCommand,
}

#[derive(Subcommand, Debug, Clone)]
enum TargetCommand {
    /// Target nodes by directly specifying their WebSocket endpoints
    #[command(
        after_long_help = "Examples:\n  spammer ws\n  spammer ws --targets ws://127.0.0.1:8546,ws://127.0.0.1:9546\n"
    )]
    Ws {
        /// Explicit targets for this command.
        #[arg(long, value_delimiter = ',')]
        targets: Option<Vec<String>>,
    },
    /// Target nodes by name, using a nodes metadata file.
    ///
    /// If no node names are provided, all nodes from the file are used.
    #[command(
        after_long_help = "Examples:\n  spammer nodes --nodes-path some/path/nodes.json\n  spammer nodes --nodes-path some/path/nodes.json --targets validator1,validator2\n"
    )]
    Nodes {
        /// File with node metadata used to resolve node names to WebSocket
        /// endpoints.
        /// You can look at the .quake/<testnet-name>/nodes.json file to understand
        /// the format of the nodes metadata file. This file is generated by the
        /// `quake setup` command.
        #[arg(short = 'f', long, required = true)]
        nodes_path: String,
        /// Explicit targets for this command.
        #[arg(long, value_delimiter = ',')]
        targets: Option<Vec<String>>,
    },
}

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();

    let silent = cli.args.silent || cli.verbosity.is_silent();

    // Initialize tracing unless running silently.
    if !silent {
        let level = cli.verbosity.tracing_level_filter();
        let filter = EnvFilter::builder()
            .with_default_directive(level.into())
            .from_env()?
            .add_directive("hyper_util::client=info".parse()?)
            .add_directive("arc_node_consensus_cli::new=info".parse()?);
        let subscriber = tracing_subscriber::fmt()
            .with_max_level(level)
            .with_ansi(std::io::stdout().is_terminal())
            .with_env_filter(filter)
            .finish();

        tracing::subscriber::set_global_default(subscriber)
            .context("Failed to set tracing subscriber")?;
    }

    tracing::info!(
        version = arc_version::GIT_VERSION,
        commit = arc_version::GIT_COMMIT_HASH,
        "Spammer starting"
    );

    let config = cli.args.to_config(silent, cli.fire_and_forget);
    config.validate()?;

    // Build the WebSocket URLs of the target nodes
    let target_ws_urls = match cli.command {
        TargetCommand::Ws { targets } => {
            let target_nodes = targets.unwrap_or_else(|| vec![DEFAULT_WS_TARGET.to_string()]);
            ws_urls_from_strings(target_nodes)
        }
        TargetCommand::Nodes {
            nodes_path,
            targets,
        } => {
            let target_nodes = targets.unwrap_or_default();
            ws_urls_from_file(&nodes_path, target_nodes)?
        }
    };

    let summary_json_path = cli.args.summary_json.clone();
    let state_out_path = cli.args.state_out.clone();
    let state_in_path = cli.args.state_in.clone();

    // Backpressure mode moves every TxGenerator into its TxSender, so
    // `Spammer::run_capturing_state` returns an empty `SpammerState`.
    // Writing that to --state-out would let a downstream --state-in
    // "succeed" as a silent no-op run, hiding the upstream misconfig
    // (see `new_resuming` for the matching guard).
    if state_out_path.is_some() && !cli.fire_and_forget {
        eyre::bail!(
            "--state-out requires --fire-and-forget; backpressure mode cannot capture generator state"
        );
    }

    // If `--state-in` was provided, resume from the persisted SpammerState and
    // skip fresh account initialisation. Otherwise spin up generators normally.
    let spammer = if let Some(path) = state_in_path {
        let json = fs::read_to_string(&path)
            .wrap_err_with(|| format!("Failed to read --state-in from {}", path.display()))?;
        let state: spammer::SpammerState = serde_json::from_str(&json)
            .wrap_err_with(|| format!("Failed to parse --state-in from {}", path.display()))?;
        let resume_config = spammer::ResumeConfig::from(&config);
        Spammer::new_resuming(target_ws_urls, state, &resume_config).await?
    } else {
        Spammer::new(target_ws_urls, &config).await?
    };
    let result = spammer.run_capturing_state().await?;

    // Drop a JSON summary at the caller-provided path. Used by orchestrators
    // (e.g. `quake run saturation`) to recover phase metrics without parsing
    // spammer stdout. Independent of the latency CSV (`--csv-dir`).
    if let Some(path) = summary_json_path {
        let summary = spammer::SpammerSummary::from(&result);
        let json =
            serde_json::to_string_pretty(&summary).wrap_err("Failed to serialise summary JSON")?;
        write_atomic(&json, &path, "summary-json")?;
    }

    // Persist the captured SpammerState so a subsequent `--state-in` invocation
    // can resume without re-initialising accounts.
    if let Some(path) = state_out_path {
        let json = serde_json::to_string(&result.state)
            .wrap_err("Failed to serialise SpammerState JSON")?;
        write_atomic(&json, &path, "state-out")?;
    }

    Ok(())
}

/// Write `contents` to `path` atomically: stage into a tempfile in the target
/// directory and rename on success. The `label` is included in error messages
/// so a failed `--state-out` write isn't confused with a failed
/// `--summary-json` write.
fn write_atomic(contents: &str, path: &Path, label: &str) -> Result<()> {
    let parent = path.parent().filter(|p| !p.as_os_str().is_empty());
    if let Some(p) = parent {
        fs::create_dir_all(p)
            .wrap_err_with(|| format!("Failed to create parent dir {} for {label}", p.display()))?;
    }
    // Tempfile must be on the same filesystem as the destination for
    // rename to be atomic; using the parent dir guarantees that.
    let dir = parent.unwrap_or_else(|| Path::new("."));
    let mut tmp = tempfile::NamedTempFile::new_in(dir)
        .wrap_err_with(|| format!("Failed to create tempfile for {label} in {}", dir.display()))?;
    tmp.write_all(contents.as_bytes())
        .wrap_err_with(|| format!("Failed to write {label} tempfile"))?;
    // tempfile defaults to mode 0o600 (owner-only). Remote orchestrators
    // SCP these files as an unprivileged user from a path the spammer
    // writes as root (inside the docker wrapper on CC), so 0o600 makes the
    // file unreadable. Match the broader-readable default the prior
    // non-atomic `fs::write` produced via umask.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        tmp.as_file()
            .set_permissions(std::fs::Permissions::from_mode(0o644))
            .wrap_err_with(|| format!("Failed to chmod {label} tempfile"))?;
    }
    tmp.persist(path).map_err(|e| {
        eyre::eyre!(
            "Failed to persist {label} to {}: {}",
            path.display(),
            e.error
        )
    })?;
    Ok(())
}

// Build the WebSocket URLs of the target nodes from the list of IP addresses and ports
fn ws_urls_from_strings(target_nodes: Vec<String>) -> Vec<(String, Url)> {
    target_nodes
        .into_iter()
        .map(|s| (s.clone(), ws_url_from_str(s)))
        .collect()
}

fn ws_url_from_str(ip_port: String) -> Url {
    let url_str = if !ip_port.starts_with("ws://") {
        format!("ws://{ip_port}")
    } else {
        ip_port
    };
    Url::parse(&url_str).unwrap()
}

// Read the file with node metadata and obtain the WebSocket URLs of the target nodes
fn ws_urls_from_file(nodes_path: &str, target_nodes: Vec<String>) -> Result<Vec<(String, Url)>> {
    let nodes_metadata = fs::read_to_string(nodes_path)
        .map_err(|e| eyre::eyre!("Failed to read {nodes_path}: {e}"))?;
    let nodes_metadata = serde_json::from_str::<Vec<NodeMetadata>>(&nodes_metadata)?;

    // If no target nodes are provided, use all nodes from the file.
    if target_nodes.is_empty() {
        let result: Vec<(String, Url)> = nodes_metadata
            .into_iter()
            .map(|node| (node.name.clone(), node.execution.ws_url.clone()))
            .collect();
        return Ok(result);
    }

    // Otherwise, validate that all requested names exist in the metadata file.
    // Return an error on the first missing name.
    let nodes_map: HashMap<&str, &NodeMetadata> = nodes_metadata
        .iter()
        .map(|n| (n.name.as_str(), n))
        .collect();

    let mut result = Vec::with_capacity(target_nodes.len());
    for name in target_nodes {
        match nodes_map.get(name.as_str()) {
            Some(node) => result.push((name, node.execution.ws_url.clone())),
            None => eyre::bail!("Target node not found in metadata file {nodes_path}: {name}"),
        }
    }

    Ok(result)
}

#[derive(Deserialize, Clone, Debug)]
struct NodeMetadata {
    name: String,
    execution: ExecutionContainer,
}

#[derive(Deserialize, Clone, Debug)]
struct ExecutionContainer {
    ws_url: Url,
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::error::ErrorKind;
    use std::path::PathBuf;

    fn write_temp_nodes_json(contents: &str) -> PathBuf {
        let mut path = std::env::temp_dir();
        let unique = format!(
            "spammer-nodes-{}-{}.json",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .expect("system time after unix epoch")
                .as_nanos()
        );
        path.push(unique);
        std::fs::write(&path, contents).expect("write temp nodes json");
        path
    }

    #[test]
    fn ws_url_from_str_adds_ws_scheme_if_missing() {
        let url = ws_url_from_str("127.0.0.1:8546".to_string());
        assert_eq!(url.as_str(), "ws://127.0.0.1:8546/");
    }

    #[test]
    fn ws_url_from_str_parses_endpoint() {
        let url = ws_url_from_str("ws://127.0.0.1:8546".to_string());
        assert_eq!(url.as_str(), "ws://127.0.0.1:8546/");
    }

    #[test]
    fn ws_urls_from_strings_parses_endpoints() {
        let urls = ws_urls_from_strings(vec![
            "127.0.0.1:8546".to_string(),
            "ws://127.0.0.1:9546".to_string(),
        ]);

        assert_eq!(urls.len(), 2);
        assert_eq!(urls[0].0, "127.0.0.1:8546");
        assert_eq!(urls[0].1.as_str(), "ws://127.0.0.1:8546/");
        assert_eq!(urls[1].0, "ws://127.0.0.1:9546");
        assert_eq!(urls[1].1.as_str(), "ws://127.0.0.1:9546/");
    }

    #[test]
    fn ws_urls_from_file_parses_endpoints() -> Result<()> {
        let nodes_json = r#"
[
  {"name":"validator1","execution":{"ws_url":"ws://127.0.0.1:8546"}},
  {"name":"validator2","execution":{"ws_url":"ws://127.0.0.1:9546"}}
]
"#;
        let path = write_temp_nodes_json(nodes_json);

        // When no names are provided, all nodes from the file are selected.
        let all = ws_urls_from_file(path.to_str().unwrap(), vec![])?;
        let want_nodes = vec![
            (
                "validator1".to_string(),
                Url::parse("ws://127.0.0.1:8546/").unwrap(),
            ),
            (
                "validator2".to_string(),
                Url::parse("ws://127.0.0.1:9546/").unwrap(),
            ),
        ];
        assert_eq!(all, want_nodes);

        // When a subset of names is provided, only those are returned.
        let subset = ws_urls_from_file(path.to_str().unwrap(), vec!["validator2".to_string()])?;
        let want_subset = vec![(
            "validator2".to_string(),
            Url::parse("ws://127.0.0.1:9546/").unwrap(),
        )];
        assert_eq!(subset, want_subset);

        // Unknown names return an error.
        let err = ws_urls_from_file(path.to_str().unwrap(), vec!["does-not-exist".to_string()])
            .unwrap_err();
        assert!(
            err.to_string().contains("Target node not found"),
            "unexpected error: {err:?}"
        );

        let _ = std::fs::remove_file(path);
        Ok(())
    }

    #[test]
    fn cli_parses_ws_subcommand_with_targets_flag() {
        let cli = Cli::try_parse_from([
            "spammer",
            "ws",
            "--targets",
            "127.0.0.1:8546,ws://127.0.0.1:9546",
        ])
        .expect("parsing ws subcommand with --targets");

        match cli.command {
            TargetCommand::Ws { targets } => {
                assert_eq!(
                    targets,
                    Some(vec![
                        "127.0.0.1:8546".to_string(),
                        "ws://127.0.0.1:9546".to_string(),
                    ])
                );
            }
            _ => panic!("expected ws subcommand"),
        }
    }

    #[test]
    fn cli_rejects_ws_positional_targets() {
        let err = match Cli::try_parse_from(["spammer", "ws", "127.0.0.1:8546"]) {
            Ok(_) => panic!("positional ws targets must be rejected"),
            Err(err) => err,
        };

        assert_eq!(err.kind(), ErrorKind::UnknownArgument);
        assert!(err.to_string().contains("127.0.0.1:8546"));
    }

    #[test]
    fn cli_parses_nodes_subcommand_with_targets_flag() {
        let cli = Cli::try_parse_from([
            "spammer",
            "nodes",
            "--nodes-path",
            "nodes.json",
            "--targets",
            "validator1,validator2",
        ])
        .expect("parsing nodes subcommand with --targets");

        match cli.command {
            TargetCommand::Nodes {
                nodes_path,
                targets,
            } => {
                assert_eq!(nodes_path, "nodes.json");
                assert_eq!(
                    targets,
                    Some(vec!["validator1".to_string(), "validator2".to_string()])
                );
            }
            _ => panic!("expected nodes subcommand"),
        }
    }

    #[test]
    fn cli_rejects_nodes_positional_targets() {
        let err = match Cli::try_parse_from([
            "spammer",
            "nodes",
            "--nodes-path",
            "nodes.json",
            "validator1",
        ]) {
            Ok(_) => panic!("positional node targets must be rejected"),
            Err(err) => err,
        };

        assert_eq!(err.kind(), ErrorKind::UnknownArgument);
        assert!(err.to_string().contains("validator1"));
    }

    #[test]
    fn cli_accepts_shared_flags_after_nodes_subcommand() {
        let cli = Cli::try_parse_from([
            "spammer",
            "nodes",
            "--nodes-path",
            "nodes.json",
            "--targets",
            "validator1,validator2",
            "--rate",
            "42",
        ])
        .expect("parsing shared flags after nodes subcommand");
        assert_eq!(cli.args.rate, 42);
    }

    #[test]
    fn cli_parses_fire_and_forget_flag() {
        // Default: fire_and_forget is false (backpressure is the default)
        let cli = Cli::try_parse_from(["spammer", "ws"]).expect("parsing ws subcommand");
        assert!(!cli.fire_and_forget);

        // Explicit: --fire-and-forget
        let cli = Cli::try_parse_from(["spammer", "ws", "--fire-and-forget"])
            .expect("parsing --fire-and-forget");
        assert!(cli.fire_and_forget);

        // Works after subcommand with other flags
        let cli = Cli::try_parse_from([
            "spammer",
            "ws",
            "--targets",
            "127.0.0.1:8546,ws://127.0.0.1:9546",
            "--fire-and-forget",
            "--rate",
            "500",
        ])
        .expect("parsing --fire-and-forget with other flags");
        assert!(cli.fire_and_forget);
        assert_eq!(cli.args.rate, 500);
    }
}
