{
 "title": "Reth database",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Persistence Save Beacon Blocks Time",
   "type": "timeseries",
   "description": "The total time Reth has spent persisting new canonical blocks that arrived via the Engine API’s forkchoice updates (i.e. beacon-driven head updates).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(reth_consensus_engine_beacon_persistence_duration_sum[$__rate_interval]) / rate(reth_consensus_engine_beacon_persistence_duration_count[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Persistence Save Blocks Time",
   "type": "timeseries",
   "description": "The total time Reth’s generic block‐persistence routine has spent writing any batch of blocks to disk, regardless of whether they came from a forkchoice update or from historical/P2P sync.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(reth_consensus_engine_persistence_save_blocks_duration_seconds_sum[$__rate_interval])/rate(reth_consensus_engine_persistence_save_blocks_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Commit Write Duration",
   "type": "timeseries",
   "description": "The time of the write phase of the commit, that is, the time spent flushing modified pages to disk under during the write transaction.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job)(rate(reth_database_transaction_commit_write_duration_seconds_sum[$__rate_interval])) / sum by (job) (rate(reth_database_transaction_commit_write_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Commit Duration",
   "type": "timeseries",
   "description": "The entire duration of a database transaction commit, from the moment the commit call is entered to when it returns.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (\n  rate(reth_database_transaction_commit_whole_duration_seconds_sum[$__rate_interval])\n)\n/\nsum by (job) (\n  rate(reth_database_transaction_commit_whole_duration_seconds_count[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Time on GC During Commit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(reth_database_transaction_commit_gc_cputime_duration_seconds_sum[$__rate_interval])) / sum by (job) (rate(reth_database_transaction_commit_gc_cputime_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Blocks in in-memory Buffer",
   "type": "gauge",
   "description": "Blocks that have been received and (in the case of canonical blocks) executed, but not yet flushed to the on-disk database.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_blockchain_tree_block_buffer_blocks",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "description": "Number of bytes the Reth process has in physical RAM right now. It excludes memory that has been swapped out or is only mapped but not loaded into RAM.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "reth_process_resident_memory_bytes",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}